version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_DATABASE: "platform"
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"  
    networks:
      - app-network
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s


  admin:
    build: ./admin
    ports:
      - "4000:4000"
    env_file:
      - ./admin/.env
    depends_on:
      mysql:
        condition: service_healthy  
    networks:
      - app-network

  client-steaming:
    build: ./client-steaming
    ports:
      - "3200:3200"
    env_file:
      - ./client-steaming/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  clientlient:
    build: ./clientlient
    ports:
      - "3001:3001"
    env_file:
      - ./clientlient/.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis-master
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - admin
      - client-steaming
      - clientlient
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
